# Vim
[[plugins]]
repo = 'Shougo/neco-vim'
on_ft = ['vim']

# JavaScript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx']

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# CSS
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# Ruby, Rails
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# Python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

